// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPgit latform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD44yrtkszok5ecgSgy9syq5zhfGMN_gyk',
    appId: '1:1049085027174:web:a739cc28b3d85f56939ea7',
    messagingSenderId: '1049085027174',
    projectId: 'emeron-29050',
    authDomain: 'emeron-29050.firebaseapp.com',
    storageBucket: 'emeron-29050.firebasestorage.app',
    measurementId: 'G-P78N994Q4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHVfMFOm39I0-rBe7v5txDk5iPIccoUVk',
    appId: '1:1049085027174:android:a40aa08abba15854939ea7',
    messagingSenderId: '1049085027174',
    projectId: 'emeron-29050',
    storageBucket: 'emeron-29050.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcv5zq_JIkY0kkH9sRAC1EwKErH6z62pw',
    appId: '1:1049085027174:ios:5461194b43c329f3939ea7',
    messagingSenderId: '1049085027174',
    projectId: 'emeron-29050',
    storageBucket: 'emeron-29050.firebasestorage.app',
    iosBundleId: 'com.example.emeron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcv5zq_JIkY0kkH9sRAC1EwKErH6z62pw',
    appId: '1:1049085027174:ios:f8ea69a0901d5790939ea7',
    messagingSenderId: '1049085027174',
    projectId: 'emeron-29050',
    storageBucket: 'emeron-29050.firebasestorage.app',
    iosBundleId: 'com.emeron.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD44yrtkszok5ecgSgy9syq5zhfGMN_gyk',
    appId: '1:1049085027174:web:97cdb4a914c14b57939ea7',
    messagingSenderId: '1049085027174',
    projectId: 'emeron-29050',
    authDomain: 'emeron-29050.firebaseapp.com',
    storageBucket: 'emeron-29050.firebasestorage.app',
    measurementId: 'G-KE72JM93B1',
  );
}
